# Site settings
name: Gianfranco Frau
title: Gianfranco Frau &bull; developer
description: ""
baseurl: "/gianfrancofrau"
url: "http://0.0.0.0:4000"

# Build settings
markdown: kramdown
permalinks: pretty
