# Site settings
name: Gianfranco Frau
title: Your awesome title
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://0.0.0.0:4000"

# Build settings
markdown: kramdown
permalinks: pretty
